spring.application.name=coffee-roastery-management
server.port=8080

# Configuration Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/coffee_roastery_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuration JWT
jwt.secret=g8BfFJvdedbxXRnZVBvYnLcnUiNizqSaWb259KVN8p+47t2nWeml/+vzaTEBfIvVu60A832Wvf4syIEMej2C9w==
jwt.expiration=86400000

# Configuration Upload de fichiers
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB